# This file tells scons what files make up SWEGUI

import sys

Import('env')

sourceFiles = ['SFMLWidget.cpp', 'SFMLWidgetGlade.cpp']

for i in sourceFiles:
    env.src_files.append(env.Object(i))

Export('env')
