# This file tells scons what files make up the GLADE/GTK+ SFML widget shared library

import sys

Import('env_library')

# List sources
sourceFiles = ['SFMLWidget.cpp', 'SFMLWidgetEx.cpp', 'SFMLWidgetGlade.cpp']
for i in sourceFiles: env_library.src_files.append(env_library.Object(i))

# Build binary
env_library['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME'] = 1
env_library.Append(CCFLAGS=['-fPIC'])
env_library.SharedLibrary(env_library.library_name, env_library.src_files)

# Copy binary
Install('#'+env_library['buildDir']+'/packet/lib', 'lib'+env_library.library_name+'.so')

# Copy catalog
Install('#'+env_library['buildDir']+'/packet/lib', 'SFMLWidgets.xml')