# This file tells scons what files make up SWEGUI

Import('env')

# Glob sources
for s in ['.', 'resources', 'widgets', 'probe', 'renderer' ]: 
    env.src_files += [Glob(s + '/*.cpp')]
env.src_files += ['reader/NetCdfReader.cpp']
# Add resources
env.src_files += env.GtkResBld('ui/main.gresource.xml')

# Add search path for swe datareader
Repository('#submodules/swe')
env.Append(CPPPATH=['#submodules/swe/src'])

# Build binary
prog = env.Program(env.program_name, env.src_files)