# This file tells scons what files make up SWEGUI

import sys

Import('env')

sourceFiles = ['main.cpp', 'gtkmm_swe_application.cc', 'gtkmm_swe_guiapplicationwindow.cc']

for i in sourceFiles:
    env.src_files.append(env.Object(i))

# Define tests
env.CxxTest('SWEGUITests', ['unit_tests/SWEGUITests.t.h'])

Export('env')
