# This file tells scons what files make up the GLADE/GTK+ SFML widget shared library

import sys

Import('env_library')

# List resources
sourceFiles_res = ['ui/datafield.glade']
res_code = '#'+env_library['buildDir']+'/'+env_library['buildDir']+'_'+env_library.library_name+'/ui/resources_widgets.c'
res_xml = 'ui/widgets.gresource.xml'
Depends(res_xml, sourceFiles_res)
env_library.GtkResBld(res_code, res_xml)

# List sources
sourceFiles_lib = ['WidgetsGlade.cpp']
sourceFiles_lib += ['SFMLWidget.cpp', 'SFMLWidgetEx.cpp']
sourceFiles_lib += ['DataFieldWidget.cpp', 'DataFieldWidgetEx.cpp']
sourceFiles_lib += [res_code]
env_library.src_files = []
for i in sourceFiles_lib: env_library.src_files.append(env_library.Object(i))

# Build binary
env_library['STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME'] = 1
env_library.Append(CCFLAGS=['-fPIC'])
env_library.SharedLibrary(env_library.library_name, env_library.src_files)

# Copy binary
Install('#'+env_library['buildDir']+'/packet/lib', 'lib'+env_library.library_name+'.so')

# Copy catalog
Install('#'+env_library['buildDir']+'/packet/lib', 'ui/sweguiwidgetsglade.xml')